In [ ]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        line = input().split()
        name, scores = line[0], line[1:]
        o=len(scores)
        scores = map(float, scores)
        student_marks[name] = scores
    query_name = input()
    query_scores = student_marks[query_name]
    print("{0:.2f}".format(sum(query_scores)/(o)))

3
Krishna 67 68 69
Arjun 70 98 63
Malika 52 56 60
Arjun
77.00


In [ ]:
n=input().split()
number,stamps=n[0],n[1:]
stamps=set(stamps)
print(len(stamps))

2 just bhai yo bhai
3


In [ ]:
n =input()
stamps=input()
stamps=set(stamps)
STDOUT=len(stamps)
print(STDOUT)

2
Uk France France Germany
12


In [ ]:
stamps

{'China', 'France', 'New', 'UK', 'USA', 'Zealand'}

In [ ]:
n=input().split()
number,stamps=n[0],n[1:]
stamps=set(stamps)
print(len(stamps))


7 UK China USA France New Zealand UK France
6


In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
n=input()
stamps=input().split(' ')
stamps=set(stamps)

print(len(stamps))

7
UK China USA France New Zealand UK France
6


In [ ]:
print(stamps)

{'New', 'France', 'USA', 'UK', 'Zealand', 'China'}


In [ ]:
'UK China USA France New Zealand'print(stamps)

["'UK China USA France New Zealand'"]


In [ ]:
7stamps

{'UK China USA France New Zealand UK France'}

In [ ]:
print(len(set([str(input()) for x in range(int(input()))])))

7
uk
france
germany
india
india
ek
uk
5


In [ ]:
for x in range(int(input())):
  x=set(str(input()))
print(len(x))  

7
uk
china
new zealand
usa
france
uk
rance
5


In [ ]:
for x in range(int(input())):
  x=set(str(input()))
print(len(x)) 

7
uk
china
usa
france
new zealand
ek
uk
2


In [ ]:
length = int(input())
data = set()

for i in range(0, length):
    data.add(input())
    
print (len(data))

2
uk
new zealand
2


In [ ]:
print(data)

{'uk', 'new zealand'}


In [ ]:
n = int(input("Enter number of rows: "))

for i in range(1,n+1):
    for j in range(1, i+1):
        print(j, end="")
    print()
  

Enter number of rows: 5
1
12
123
1234
12345


**Set .discard()**

In [ ]:
n=int(input())

s = set(map(int,input().split()))

N=int(input())

for i in range(N) :
  choice=input().split()
  if choice[0]=="pop":
      s.pop()
  elif choice[0]=="remove":
    s.remove(int(choice[1]))
  elif choice[0]=="discard":
    s.discard(int(choice[1]))
print(sum(s))

9
1 2 3 4 5 6 7 8 9
10
pop
remove 9
discard 9
discard 8
remove 7
pop
discard 6
remove 5
pop
discard 5
4


In [ ]:
print(s)

{4}


In [ ]:
n=input()
l=[]
for i in range(n):
  s=input().split
  command=s[0]
  N=s[1:]
  if command=='insert'

**Set_mutations**

In [ ]:
_ = int(input())
inp1 = set(map(int, input().split()))
N = int(input())

for _ in range(N):
    cmd, _ = input().split()
    inp2 = set(map(int, input().split()))
    if(cmd == "intersection_update"):
        inp1.intersection_update(inp2)
    elif(cmd == "update"):
        inp1.update(inp2)
    elif(cmd == "symmetric_difference_update"):
        inp1.symmetric_difference_update(inp2)
    elif(cmd == "difference_update"):
        inp1.difference_update(inp2)

print(sum(inp1))

16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
2 3 5 6 8 9 1 4 7 11
update 2
55 66
symmetric_difference_update 5
22 7 35 62 58
difference_update 7
11 22 35 55 58 62 66
38


**Set.difference()**

In [ ]:
n1 = int(input())
set_1 = set(map(int,input().split()))
n2 = int(input())
set_2 = set(map(int,input().split()))
print(len(set_1.difference(set_2)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
4


**Tuples**

In [ ]:
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())
    integer_list=list(integer_list)
    print(hash(tuple(integer_list)))

2
1 2
3713081631934410656


**List Comprehension**

In [ ]:
if __name__ == '__main__':
    x, y, z, n = (int(input()) for i in range(4))
    print ([[a,b,c] for a in range(0,x+1) for b in range(0,y+1) for c in range(0,z+1) if a + b + c != n ])

1
1
2
3
[[0, 0, 0], [0, 0, 1], [0, 0, 2], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 2]]


In [ ]:
x=int(input())
y=int(input())
z=int(input())
n=int(input())
for i in range(x+1):
  for j in range(y+1):
    for k in range(z+1):
      if i+j+k!=n:
        print([i,j,k])

1
2
2
3
[0, 0, 0]
[0, 0, 1]
[0, 0, 2]
[0, 1, 0]
[0, 1, 1]
[0, 2, 0]
[0, 2, 2]
[1, 0, 0]
[1, 0, 1]
[1, 1, 0]
[1, 1, 2]
[1, 2, 1]
[1, 2, 2]


**Lists**

In [ ]:
N = int(input())
lis=list()
for _ in range(N):
  s=input().strip().split(" ")
  if s[0]=="insert":
    lis.insert(int(s[1]),int(s[2]))
  elif s[0]=="print":
    print(lis)
  elif s[0]=="remove":
    lis.remove(int(s[1]))
  elif s[0]=="append":
    lis.append(int(s[1]))
  elif s[0]=="sort":
    lis.sort()
  elif s[0]=="pop":
    lis.pop()
  elif s[0]=="reverse":
    lis.reverse()
print(lis)    

3
append 1
append 2
insert 2 1
[1, 2, 1]


**String swap case**

In [ ]:
s=input().swapcase()
print(s)

abCD
ABcd


In [ ]:
s=input()
result=''
for char in s:
  if char==char.lower():
    result+=char.upper()
  else:
    result+=char.lower()
print(result)    

abCD
ABcd


In [ ]:
def swap_case(s):
    result = ""
    for letter in s:
        if letter == letter.upper():
            result += letter.lower()
        else:
            result += letter.upper()
    return result
    
    
if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

abCD
ABcd


**String Formatting**

In [ ]:
def print_formatted(number):
   
  width = len("{0:b}".format(n))
  for i in range(1,n+1):
    print("{0:{width}d} {0:{width}o} {0:{width}X} {0:{width}b}".format(i, width=width))

if __name__ == '__main__':
  n = int(input())
  print_formatted(n)

17
    1     1     1     1
    2     2     2    10
    3     3     3    11
    4     4     4   100
    5     5     5   101
    6     6     6   110
    7     7     7   111
    8    10     8  1000
    9    11     9  1001
   10    12     A  1010
   11    13     B  1011
   12    14     C  1100
   13    15     D  1101
   14    16     E  1110
   15    17     F  1111
   16    20    10 10000
   17    21    11 10001


**String Split and Join**

In [ ]:
def split_and_join(line):
    line=line.split(' ')
    line='-'.join(line)
    return line
    

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

dsfsdsd dsf
dsfsdsd-dsf


In [ ]:
result

'd-f-s-d'

**Strings What's your name**

In [ ]:
#
# Complete the 'print_full_name' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING first
#  2. STRING last
#

def print_full_name(first, last):
    name=first_name +' '+ last_name
    op='Hello ' + name + '! You just delved into python.'
    print(op)

if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

taran
singh
Hello taran singh! You just delved into python.


**String: Find a String**

In [ ]:
def count_substring(string, sub_string):
  count = 0
  while sub_string in string:
    i = string.find(sub_string)
    string = string[:i] + string[i + 1:]
    count += 1
  return count
  

if __name__ == '__main__':
  string = input().strip()
  sub_string = input().strip()
    
  count = count_substring(string, sub_string)
  print(count)

tararan
ara
2


**String Mutations**

In [ ]:
def mutate_string(string, position, character):
  string=s[:int(i)] + c + s[int(i)+1:]
  
  return string 

if __name__ == '__main__':
  s = input()
  i, c = input().split()
  s_new = mutate_string(s, int(i), c)
  print(s_new)

abcraeads
5 k
abcrakads


**Alphabet Rangoli**

In [ ]:
def print_rangoli(size):
  import string
  alpha = string.ascii_lowercase

  
  L = []
  for i in range(n):
    s = "-".join(alpha[i:n])
    L.append((s[::-1]+s[1:]).center(4*n-3, "-"))
    print('\n'.join(L[:0:-1]+L))

if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)


4
d-c-b-a-b-c-d
--d-c-b-c-d--
d-c-b-a-b-c-d
--d-c-b-c-d--
----d-c-d----
--d-c-b-c-d--
d-c-b-a-b-c-d
--d-c-b-c-d--
----d-c-d----
------d------
----d-c-d----
--d-c-b-c-d--
d-c-b-a-b-c-d
--d-c-b-c-d--
----d-c-d----
------d------


**String Validators**

In [ ]:
str = input()
print (any(c.isalnum()  for c in str))
print (any(c.isalpha() for c in str))
print (any(c.isdigit() for c in str))
print (any(c.islower() for c in str))
print (any(c.isupper() for c in str))

aQ1
True
True
True
True
True


**Strings: Capitalize**

In [ ]:
def solve(s):
  s = list(s.split(' '))
  p=[]
  for i in s:
    if i.isalpha():
      p.append(i[0].upper()+i[1:]+" ")
    else:
      p.append(i)
      p.append(" ")            
  p="".join(p)  
  return p

In [ ]:
solve('hello world')

'Hello World '

**Text Wrap**

In [ ]:
import textwrap

def wrap(string, max_width):
  l= list()
  for i in range(0,len(string),max_width):
     l.append(string[i:i+max_width])
  return "\n".join(l)



if __name__ == '__main__':
  string, max_width = input(), int(input())
  result = wrap(string, max_width)
  print(result)

sadfsddsga
2
sa
df
sd
ds
ga


**Strings: Minion Game**

In [ ]:
s = input()

vowels = 'AEIOU'

kscore = 0
stscore = 0
for i in range(len(s)):
  if s[i] in vowels:
    kscore += (len(s)-i)
  else:
    stscore += (len(s)-i)

if kscore > stscore:
  print("Kevin", kscore)
elif kscore < stscore:
  print("Stuart", stscore)
else:
  print("Draw")

BANANA
Stuart 12


**Math : Mod Divmod**

In [ ]:
from math import floor
a=int(input())
b=int(input())
print(floor(a/b))
print(a%b)
print(divmod(a,b))


12
10
1
2
(1, 2)


**Math: Pow Mod Power**

In [ ]:
a=int(input())

b=int(input())

c=int(input())
print(pow(a,b))
print(pow(a,b,c))


2
4
2
16
0


**Triangle quest**

In [ ]:
for i in range(1,int(input())+1):
  print(int((10**(i)/9)*i))

4
1
22
333
4444


**Triangle quest 2**

In [ ]:
for x in range(1,int(input())+1):
  print(((10**x - 1)//9)**2)

9
1
121
12321
1234321
123454321
12345654321
1234567654321
123456787654321
12345678987654321


In [ ]:
for i in range(1,int(input())+1): #More than 2 lines will result in 0 score. Do not leave a blank line also
   print(int((10**i-1)/9)**2)

9
1
121
12321
1234321
123454321
12345654321
1234567654321
123456787654321
12345678987654321


**Integers come in all sizes**

In [ ]:
a=int(input())
b=int(input())
c=int(input())
d=int(input())
print((a**b)+(c**d))

1
2
3
4
82


**Polar Coordinates**

In [ ]:
import cmath
a=input()
print(*cmath.polar(complex(a)),sep='\n')


1+2j
2.23606797749979
1.1071487177940904


**String Formatting**

In [ ]:
n =int(input())
width = len("{0:b}".format(n))
for i in range(1,n+1):
  print("{0:{width}d} {0:{width}o} {0:{width}X} {0:{width}b}".format(i, width=width))


6
1 1 1 1
2 2 2 10
3 3 3 11
4 4 4 100
5 5 5 101
6 6 6 110


**Introduction to sets**

In [ ]:
def average(array):
  set_arr=set(arr)
  res=sum(set_arr)/len(set_arr)
  return res

if __name__ == '__main__':
  n = int(input())
  arr = list(map(int, input().split()))
  result = average(arr)
  print(result)

10
161 182 161 154 176 170 167 171 170 174
169.375


**No Idea**

In [ ]:
n, m = input().split()

sc_ar = input().split()

A = set(input().split())
B = set(input().split())
print (sum([(i in A) - (i in B) for i in sc_ar]))

 2 3
1 5 3
1 7 8
5 3
-1


**Symmetric Difference**

In [ ]:
a,b=(int(input()),input().split())
c,d=(int(input()),input().split())
x=set(b)
y=set(d)
p=y.difference(x)
q=x.difference(y)
r=p.union(q)
print ('\n'.join(sorted(r, key=int)))


4
2 5 3 1
4
5 6 7 1
2
7
3
6


**Set.discard()**


In [ ]:
n=int(input())
S=set(map(int,input().split()))
N=int(input())
for i in range(N):
  s=input().strip().split(" ")
  if s[0]=="insert":
    S.insert(int(s[1]),int(s[2]))
  elif s[0]=="print":
    print(StopAsyncIteration)
  elif s[0]=="remove":
    S.remove(int(s[1]))
  elif s[0]=='discard':
    S.discard(int(s[1]))
  elif s[0]=="append":
    S.append(int(s[1]))
  elif s[0]=="sort":
    S.sort()
  elif s[0]=="pop":
    S.pop()
  elif s[0]=="reverse":
    S.reverse()
print(sum(S))

4
1 2 3 4
3
remove 1
pop
discard 1
7


**Set.union()**

In [ ]:
a=(int(input()))
x=set(input().split())
c=(int(input()))
y=set(input().split())
p=x.union(y)
print(len(p))

4
1 2 3 4
4 
3 4 5 6
6


**Set.intersection()**

In [ ]:
a=(int(input()))
x=set(input().split())
c=(int(input()))
y=set(input().split())
p=x.intersection(y)
print(len(p))

4
1 2 3 4
4
3 4 5 6
2


**itertools.product()**

In [ ]:
import itertools

A = [int(x) for x in input().split()]
B = [int(y) for y in input().split()]

print(*itertools.product(A, B))

3 4
4 2
(3, 4) (3, 2) (4, 4) (4, 2)


In [ ]:
from itertools import product
a=input().split()
b=input().split()
for i in range(len(a)):
  for j in range(len(b)):
    print(*product(a[i],b[j]))


3 4
2 3
('3', '2')
('3', '3')
('4', '2')
('4', '3')


**itertools.permutations**

In [ ]:
from itertools import permutations
s,n = input().split()
print(*[''.join(i) for i in permutations(sorted(s),int(n))],sep='\n')

HACK 2
AC
AH
AK
CA
CH
CK
HA
HC
HK
KA
KC
KH


In [ ]:
print(*permutations('JACK',4))

('J', 'A', 'C', 'K') ('J', 'A', 'K', 'C') ('J', 'C', 'A', 'K') ('J', 'C', 'K', 'A') ('J', 'K', 'A', 'C') ('J', 'K', 'C', 'A') ('A', 'J', 'C', 'K') ('A', 'J', 'K', 'C') ('A', 'C', 'J', 'K') ('A', 'C', 'K', 'J') ('A', 'K', 'J', 'C') ('A', 'K', 'C', 'J') ('C', 'J', 'A', 'K') ('C', 'J', 'K', 'A') ('C', 'A', 'J', 'K') ('C', 'A', 'K', 'J') ('C', 'K', 'J', 'A') ('C', 'K', 'A', 'J') ('K', 'J', 'A', 'C') ('K', 'J', 'C', 'A') ('K', 'A', 'J', 'C') ('K', 'A', 'C', 'J') ('K', 'C', 'J', 'A') ('K', 'C', 'A', 'J')


**itertools.combinations**

In [ ]:
from itertools import combinations
s,n = input().split()
for i in range(1,int(n)+1):
  for j in combinations(sorted(s),i):
    print(''.join(j))

hack 2
a
c
h
k
ac
ah
ak
ch
ck
hk


In [ ]:
from itertools import combinations_with_replacement
s,n = input().split()
print(*[''.join(i) for i in combinations_with_replacement(sorted(s),int(n))],sep='\n')

HACK 2
AA
AC
AH
AK
CC
CH
CK
HH
HK
KK


In [ ]:
a=set(input())
b=int(input())
c=set(input())
d=set(input())
if a in c and c in d:
  print(True)
else:
  print(False)

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


In [ ]:
A = set(input().split())

for _ in range(int(input())):
    if not A.issuperset(set(input().split())):
        print(False)
        break
else:
    print(True)

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


**Numpy Concatenate**

In [ ]:
import numpy as np
N,M,P = map(int,input().split())
A = np.array([input().split() for _ in range(N)],int)
B = np.array([input().split() for _ in range(M)],int)
print(np.concatenate((A,B), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


**Numpy Shape and reshape**

In [ ]:
import numpy as np
n=input().split()

print(np.array(n,int).reshape([3,3]))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Numpy:Transpose and Flatten**

In [ ]:
n, m = map(int, input().split())
array = np.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [ ]:
import numpy as np
m,p=map(int,input().split())
a=np.ones((m,p),int)

3 3


In [ ]:
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
nums = tuple(map(int, input().split()))
print (np.zeros(nums, dtype = np.int))
print (np.ones(nums, dtype = np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


**Numpy: Mean,Var and Std**

In [13]:
import numpy

NM = input().split()
n = int(NM[0])
m = int(NM[1])
arr = []
for i in range(n):
    m = list(map(int, input().split()))
    arr.append(m)
arr = numpy.array(arr)

mean = numpy.mean(arr, axis = 1)
var = numpy.var(arr, axis = 0)
std = numpy.std(arr)

print(mean)
print(var)

rnd = numpy.around(std, 11)
print(rnd)

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


**Numpy: Linear Algebra**

In [5]:
#The first line contains the integer N.
import numpy
numpy.set_printoptions(legacy='1.13')
N = int(input())
#The next N lines contains the N space separated elements of array A.
A = numpy.array([input().strip().split() for _ in range(N)], float)

#Print the determinant of A.
print (numpy.linalg.det(A))

3
2 3 45
35 4 2
2 5 1
7410.0


**Numpy: Polynomials**

In [14]:
import numpy

a = list(map(float, input().split()))

print(numpy.polyval(a, float(input())))

1.1 2 3
4
28.6
